# Generated by Django 3.0.7 on 2022-04-30 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None'), ('Other', 'Other')], default='None', max_length=10, verbose_name='Gender')),
                ('source', models.CharField(choices=[('Quora', 'Quora'), ('Reddit', 'Reddit'), ('Survey', 'Survey')], default='Survey', max_length=20, verbose_name='Source')),
                ('time_of_infection', models.CharField(choices=[('1st Wave', '1st Wave'), ('2nd Wave', '2nd Wave'), ('Both', 'Both')], default='1st Wave', max_length=10, verbose_name='The time of Infection')),
                ('testing_date1', models.DateField(blank=True, null=True, verbose_name='Testing Date (positive result date only)')),
                ('testing_date2', models.DateField(blank=True, null=True, verbose_name='Testing Date(optional)')),
                ('experience', models.CharField(max_length=5000, verbose_name='Experience')),
                ('islongcovid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Long Covid')),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.CharField(max_length=2000, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Symtoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Reply')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_obj', to='home.CovidExperience')),
            ],
        ),
    ]
