# Generated by Django 3.0.7 on 2022-04-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symtoms',
            new_name='Symptom',
        ),
    ]
